export const apiPaths = {
  public: {
    products: "/public/products",
    productDetails: (id) => `/public/products/${id}`,
    relatedProducts: (id) => `/public/products/${id}/related`,
    categories: "/public/categories",
    subcategories: (category) =>
      `/public/categories/${category}/subcategories`,
    categoryProducts: (category ) =>
      `/public/categories/${category}/products`,
    stores: "/public/stores",
    storeDetails: (username) => `/public/stores/${username}`,
    storeProducts: (username) => `/public/stores/${username}/products`,
    search: "/public/search",
    searchSuggestions: "/public/search/suggestions",
    flashSales: "/public/flash-sales",
    flashSaleDetails: (id) => `/public/flash-sales/${id}`,
    flashSaleProducts: (id) => `/public/flash-sales/${id}/products`,
  },
  auth: {
    sellerRegister: "/auth/seller/register",
    sellerLogin: "/auth/seller/login",
    sellerActivate: "/auth/seller/activate",
    customerRegister: "/auth/customer/register",
    customerLogin: "/auth/customer/login",
    customerGoogleLogin: "/auth/customer/login/google",
    customerVerifyEmail: "/auth/customer/verify-email",
    passwordForgot: "/auth/password/forgot",
    passwordReset: "/auth/password/reset",
  },
  admin: {
    dashboard: "/admin/dashboard",
    pendingSellers: "/admin/sellers/pending",
    approveSeller: (store) => `/admin/sellers/${store}/approve`,
    rejectSeller: (store) => `/admin/sellers/${store}/reject`,
    orders: "/admin/orders",
    orderDetails: (order) => `/admin/orders/${order}`,
    updateOrder: (order) => `/admin/orders/${order}`,
  },
  seller: {
    store: "/seller/store",
    updateStore: "/seller/store",
    products: "/seller/products",
    productDetails: (id) => `/seller/products/${id}`,
    createProduct: "/seller/products",
    updateProduct: (id) => `/seller/products/${id}`,
    deleteProduct: (id) => `/seller/products/${id}`,
    toggleProductStock: (id) => `/seller/products/toggle-stock/${id}`,
    orders: "/seller/orders",
    orderDetails: (id) => `/seller/orders/${id}`,
    updateOrderStatus: (id) => `/seller/orders/${id}/status`,
    analyticsOverview: "/seller/analytics/overview",
    analyticsProducts: "/seller/analytics/products",
  },
  customer: {
    profile: "/customer/profile",
    updateProfile: "/customer/profile",
    changePassword: "/customer/profile/change-password",
    addresses: "/customer/addresses",
    wishlist: "/customer/wishlist",
    addToWishlist: "/customer/wishlist",
    removeFromWishlist: (id) => `/customer/wishlist/${id}`,
    cart: "/customer/cart",
    addToCart: "/customer/cart/add",
    updateCart: "/customer/cart/update",
    removeFromCart: (productId) => `/customer/cart/remove/${productId}`,
    clearCart: "/customer/cart/clear",
    orders: "/customer/orders",
    createOrder: "/customer/orders",
    orderDetails: (id) => `/customer/orders/${id}`,
    cancelOrder: (id) => `/customer/orders/${id}/cancel`,
    reviews: "/customer/reviews",
    createReview: "/customer/reviews",
  },
};
