export const API_PATHS = {
  PUBLIC: {
    PRODUCTS: "api/public/products",
    PRODUCT_DETAILS: (id) => `api/public/products/${id}`,
    RELATED_PRODUCTS: (id) => `api/public/products/${id}/related`,
    CATEGORIES: "api/public/categories",
    SUBCATEGORIES: (category) =>
      `api/public/categories/${category}/subcategories`,
    CATEGORY_PRODUCTS: (category) =>
      `api/public/categories/${category}/products`,
    STORES: "api/public/stores",
    STORE_DETAILS: (username) => `api/public/stores/${username}`,
    STORE_PRODUCTS: (username) => `api/public/stores/${username}/products`,
    SEARCH: "api/public/search",
    SEARCH_SUGGESTIONS: "api/public/search/suggestions",
    FLASH_SALES: "api/public/flash-sales",
    FLASH_SALE_DETAILS: (id) => `api/public/flash-sales/${id}`,
    FLASH_SALE_PRODUCTS: (id) => `api/public/flash-sales/${id}/products`,
  },
  AUTH: {
    SELLER_REGISTER: "api/auth/seller/register",
    SELLER_LOGIN: "api/auth/seller/login",
    SELLER_ACTIVATE: "api/auth/seller/activate",
    SELLER_VERIFY_EMAIL: "api/auth/seller/verify-email",
    SELLER_RESEND_VERIFICATION: "api/auth/seller/resend-verification",
    CUSTOMER_REGISTER: "api/auth/customer/register",
    CUSTOMER_LOGIN: "api/auth/customer/login",
    CUSTOMER_GOOGLE_LOGIN: "api/auth/customer/login/google",
    CUSTOMER_VERIFY_EMAIL: "api/auth/customer/verify-email",
    PASSWORD_FORGOT: "api/auth/password/forgot",
    PASSWORD_RESET: "api/auth/password/reset",
    ADMIN_LOGIN: "api/auth/admin/login",
  },
  ADMIN: {
    DASHBOARD: "api/admin/dashboard",
    PENDING_SELLERS: "api/admin/sellers/pending",
    TOGGLE_SELLER_ACTIVE: (store) => `api/admin/sellers/toggle-active/${store}`,
    APPROVE_SELLER: (store) => `api/admin/sellers/approve/${store}`,
    REJECT_SELLER: (store) => `api/admin/sellers/reject/${store}`,
    ORDERS: "api/admin/orders",
    ORDER_DETAILS: (order) => `api/admin/orders/${order}`,
    UPDATE_ORDER: (order) => `api/admin/orders/${order}`,
  },
  SELLER: {
    STORE: "api/seller/store",
    UPDATE_STORE: "api/seller/store",
    PRODUCTS: "api/seller/products",
    PRODUCT_DETAILS: (id) => `api/seller/products/${id}`,
    CREATE_PRODUCT: "api/seller/products",
    UPDATE_PRODUCT: (id) => `api/seller/products/${id}`,
    DELETE_PRODUCT: (id) => `api/seller/products/${id}`,
    TOGGLE_PRODUCT_STOCK: (id) => `api/seller/products/toggle-stock/${id}`,
    ORDERS: "api/seller/orders",
    ORDER_DETAILS: (id) => `api/seller/orders/${id}`,
    UPDATE_ORDER_STATUS: (id) => `api/seller/orders/${id}/status`,
    ANALYTICS_OVERVIEW: "api/seller/analytics/overview",
    ANALYTICS_PRODUCTS: "api/seller/analytics/products",
  },
  CUSTOMER: {
    PROFILE: "api/customer/profile",
    UPDATE_PROFILE: "api/customer/profile",
    CHANGE_PASSWORD: "api/customer/profile/change-password",
    ADDRESSES: "api/customer/addresses",
    WISHLIST: "api/customer/wishlist",
    ADD_TO_WISHLIST: "api/customer/wishlist",
    REMOVE_FROM_WISHLIST: (id) => `api/customer/wishlist/${id}`,
    CART: "api/customer/cart",
    ADD_TO_CART: "api/customer/cart/add",
    UPDATE_CART: "api/customer/cart/update",
    REMOVE_FROM_CART: (productId) => `api/customer/cart/remove/${productId}`,
    CLEAR_CART: "api/customer/cart/clear",
    ORDERS: "api/customer/orders",
    CREATE_ORDER: "api/customer/orders",
    ORDER_DETAILS: (id) => `api/customer/orders/${id}`,
    CANCEL_ORDER: (id) => `api/customer/orders/${id}/cancel`,
    REVIEWS: "api/customer/reviews",
    CREATE_REVIEW: "api/customer/reviews",
  },
};
